title: Revitalising Colville's Living Heritage
tagline: Stories, voices and connections from the northern Coromandel
description: A community led project of community stories, photographs and
  records from Colville and the Northern Coromandel Peninsula, gathered by local
  storytellers. The website development was supported by Colville Junction
  though funds from Norah Howell and Stout Trusts.
keywords: Colville; Coromandel; oral history; Northern Coromandel; community archive
author: Community Led Project, website development supported by Colville
  Junction Charitable Trust
organization-name: Colville Living Heritage
organization-logo-nav: /assets/img/Living heritage logo approved.png
url: https://colvillejunction.github.io
baseurl: /heritage
metadata: colville-living-heritage
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv
lib-assets: /assets/lib
exclude:
  - docs/
  - Rakefile
  - rakelib/
  - README.md
  - LICENSE
  - CITATION.cff
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - SECURITY.md
sass:
  style: compressed
